name: Copy Issue
on:
  issues:
    types: [opened]
    
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/user/repos/RafaelHPS/rep_clonar/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit",
            "body": "This issue was automatically created by the GitHub Action workflow. \n\n The commit hash was:.",
            "assignee": "RafaelHPS"
            }'

