name: Copy Issue
on:
  issues:
    types: [opened]
    
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/RafaelHPS/rep_clonar/issues \
          --header 'authorization: Bearer ${{ secrets.MY_API_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ github.event.issue.title }}",
            "body": "${{ github.event.issue.body }} \r\n\r\n\r\n Criado por: ${{ github.event.issue.user.login }} Issue ID: ${{ github.event.issue.id }}"
            }'

      - name: Show Repo
        run: |
          echo ${{ github.repository }}

