name: Copy Issue (
on:
  issues:
    types: [opened]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: View issue information
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "Issue body: ${{ github.event.issue.body }}"

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: RafaelHPS/rep_clonar
        ref: main
        token: ${{ secrets.MEU_TOKEN }}

    - name: Create Issue
      run: |
        gh issue create --title "My new issue" --body "Here are more details."
        


