name: Push to Destination Repository
on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: RafaelHPS/rep_clonar
          ref: main
          token: ${{ secrets.MEU_TOKEN }}

      - name: Check Files in Repository
        run: |
          pwd
          dir
          cd ..
          pwd
          dir 

      - name: Configure Git
        run: |
          git config user.email "rafael.souza123@fatec.sp.gov.br"
          git config user.name "RafaelHPS"
          git config credential.helper store

