name: Push to Destination Repository
on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: RafaelHPS/rep_clonar
          ref: main
          token: ${{ secrets.MEU_TOKEN }}

      - name: Copy files to destination repository
        run: |
          mkdir ../rep_clonar
          cp -R ./*.txt ../rep_clonar
          cd ../rep_clonar

      - name: Configure Git
        run: |
          git config user.email "rafael.souza123@fatec.sp.gov.br"
          git config user.name "RafaelHPS"
          git config credential.helper store

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Teste"
          git push origin main