name: Copy files to new repository

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy files to new repository
        run: |
          # Copy files to a new directory
          mkdir ../rep_clonar
          cp -R ./*.txt ../rep_clonar/
          echo '*.github/*' > ../rep_clonar/.gitignore
          git config --global --add safe.directory /github/workspace
          dir ../rep_clonar

      - name: Push changes to new repository
        uses: ad-m/github-push-action@v0.5.0
        with:
          directory: ../rep_clonar
          branch: main
          github_token: ${{ secrets.MEU_TOKEN }}
          repository: RafaelHPS/rep_clonar