name: Push Documents

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Git Ignore and File test
        run: |
          echo '*.github/*' > .gitignore
          echo 'abobrinha' > teste.txt
          git config --global --add safe.directory '*'

      - name: Push changes to new repository
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: main
          github_token: ${{ secrets.MEU_TOKEN }}
          repository: RafaelHPS/rep_clonar.git