name: Push to Destination Repository
on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Copy Files to Temporary Repository
        run: |
          mkdir ../new_repository
          cp -r ./* ../new_repository
          dir ../new_repository

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: RafaelHPS/rep_clonar
          ref: main
          token: ${{ secrets.MEU_TOKEN }}

      - name: Configure Git
        run: |
          git config user.email "rafael.souza123@fatec.sp.gov.br"
          git config user.name "RafaelHPS"
          git config credential.helper store
      
      - name: Create Yaml file to Replace specific words
        run: |
          cd ../new_repository
          mkdir ./.github
          mkdir ./.github/workflows/
          cp -r replace.txt .github/workflows
          mv .github/workflows/replace.txt .github/workflows/replace.yaml
          dir
          pwd

      - name: Commit and push changes
        run: |
          rm *
          dir
          cp -r ../new_repository/* .
          dir
          pwd          
          git add .
          git commit -m "Teste"
          git push origin main
