name: Copy files to new repository

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Replace Text
        run: |
          echo '*.github/*' > .gitignore
          echo 'abobrinha' > teste.txt
          git config --local user.email "rafael.souza123@fatec.sp.gov.br"
          git config --local user.name "RafaelHPS"
          git remote rename origin upstream
          git push https://${{ secrets.MEU_TOKEN }}@github.com/RafaelHPS/rep_clonar.git