name: Push Documents

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Push Documents
        run: |
          echo '*.github/*' > .gitignore
          git ls-tree --full-tree -r --name-only HEAD
          git remote rename origin upstream
          git remote add origin https://${{ secrets.MEU_TOKEN }}@github.com/RafaelHPS/rep_clonar.git
          git push origin main
