name: Replace Documents

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Replace Text
        run: |
          find .txt -type f -print0 | xargs -0 sed -i 's/foo/bar/g'
      - name: Commit Changes
        run: |
          git config --global user.email "rafael.souza123@fatec.sp.gov.br "
          git config --global user.name "RafaelHPS"
          git add .
          git commit -m "Replace text"
          git push